name: ${project.name}
version: '${project.version}'
main: wiki.creeper.farmGather.FarmGather
api-version: '1.21'
softdepend:
  - ProtocolLib
commands:
  fg:
    description: FarmGather administration command
    usage: /fg help
permissions:
  farmgather.admin:
    description: FarmGather administrator
    default: op
  farmgather.stats:
    description: Allows viewing personal FarmGather stats
    default: true
